### ISSUE TITLE
Contribution for GSSOC

### ISSUE THREAD

**Issue by rubyruins** [Technocolabs100/Stack-Overflow-Tag-Predictions#11]
Hi, I would love to contribute to this project during GSSOC 21. I have a couple ideas about how we can go about it. Could you tell me a bit more about the progress on the project and what sort of features you expect us to implement?

**Comment by virusps12** [comment]
Hello , I am interested in this issue can you please assign me this issue . I am a participant of GSSOC-21

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by KajalSinghBAGHEL** [comment]
I am GSSOC 21 participant I am a beginner and would like to work on this issue and learn new things, please assign me.
