### ISSUE TITLE
Data loading Using SQLite DB

### ISSUE THREAD

**Issue by Technocolabs100** [Technocolabs100/Stack-Overflow-Tag-Predictions#13]
To process further, We have used the simplest and most used database called SQLite. It is a Super powerful, lite weight and open-source database. The best part is that python comes inbuilt with SQLite.
More about SQLite (https://www.sqlite.org/index.html)
So instead of using a CSV file, we pump all of the data into the SQLite database and use SQL queries to process further.
we have taken all the data that is there in the CSV file and append it into the database ‘train.db’. Now we can use the created SQLite database for further process.

**Comment by utkarshxy** [comment]
Would like to work on this. Will provide pr in the form of ipynb for loading the data with SQL light.

**Comment by Technocolabs100** [comment]
Thanks, Utkarsh!
I will be assigning this issue to you.

**Comment by utkarshxy** [comment]
Hi @Technocolabs100 ! I just made the pr! Lemme know if there are any changes. 😊
#20

**Comment by utkarshxy** [comment]
HI @Technocolabs100, If there's an issue with Github loading the notebook. You can try this [Link](https://nbviewer.jupyter.org/github/utkarshxy/Stack-Overflow-Tag-Predictions-1/blob/issue%2313/stack-overflow-tag-prediction-data-loading.ipynb) to view the progress made.

**Comment by Technocolabs100** [comment]
This issue is done by Utkarsh

**Comment by onlythede** [comment]
@Technocolabs100 Hi, I guess you'll have to update labels for GSSOC'21 Leaderboard. 
level0, level1, level2 ... etc
