### ISSUE TITLE
Creating Contributing.md

### ISSUE THREAD

**Issue by honeybhardwaj** [Technocolabs100/Stack-Overflow-Tag-Predictions#22]
Hi, 
i would like to create the contribution.md file for this repo since its not been created. The file will have all the necessary details one should know to contribute in this project.

Regards
Honey Bhardwaj
GSSOC participant

**Comment by honeybhardwaj** [comment]
hi @Technocolabs100  i am done with the issue # 23 can you now assign it to me. also add gssoc label in this also.
Regard 
Honey Bhardwaj

**Comment by honeybhardwaj** [comment]
@Technocolabs100  thanks

**Comment by Technocolabs100** [comment]
This issue has been done completly
