### ISSUE TITLE
Creating Codeof conduct 

### ISSUE THREAD

**Issue by honeybhardwaj** [Technocolabs100/Stack-Overflow-Tag-Predictions#23]
hi ,
I would like to create CODEOFCONDUCT.md for this repo since its not created.
regards 
Honey Bhardwaj

**Comment by Technocolabs100** [comment]
Hello Honey,
let me know which issue you willing to work on.
you already created 2 issues 22 or this one 23.

Thanks

**Comment by honeybhardwaj** [comment]
Thanks @Technocolabs100
