### ISSUE TITLE
revamping README.md for better documentation

### ISSUE THREAD

**Issue by VivanVatsa** [Technocolabs100/Stack-Overflow-Tag-Predictions#30]
greetings, as a contributor for GSSOC'21
I would like to revamp the README.md documentation for clarity with better information & grammar.
what will my contribution focus on:

- proper structured format for easy navigation (links and flow of interaction
- add dynamic visualization to the readme (gifs & image media)
- better links presentation
- categorized heading and sub-heading for clarity
- contributors highlight 
- installation guides (how to's, do's & don'ts)
- open-source contribution procedures (forking, committing, branch checkouts, etc)

will get started, once this issue #30 is assigned.

**Comment by KajalSinghBAGHEL** [comment]
I am GSSOC participate can i work on this issue

**Comment by VivanVatsa** [comment]
@KajalSinghBAGHEL 
Most probably this project is out from the GSSOC project list. it's won't be worth the shot.
look for other projects!

regards.
